name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck kcov

    - name: Check for syntax errors (lint)
      run: make lint

    - name: Run tests with coverage
      run: |
        mkdir -p coverage
        kcov --include-path=./lib_ini.sh coverage ./run_tests.sh
        echo "Coverage report generated"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./coverage
        fail_ci_if_error: false
        verbose: true 